# Generated by Django 4.1.1 on 2023-09-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JSONUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="JSON_uploads/%d-%m-%Y-%H:%M:%S")),
                ("uploaded_on", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="rating",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
