# Generated by Django 4.1.1 on 2023-09-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_jsonupload_uploaded_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jsonupload",
            old_name="uploaded_on",
            new_name="upload_date",
        ),
    ]
