import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/providers";
import {fonts} from "@/app/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.rubik.variable}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
