import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/providers";
import {fonts} from "@/app/fonts";
import {theme} from "@/app/theme";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {Flex} from "@chakra-ui/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.rubik.variable}>
        <Providers theme={theme}>
            <Flex justifyContent={"space-between"} flexDirection={"column"}>
                <Navbar/>
                {children}
                <Footer/>
            </Flex>
        </Providers>
      </body>
    </html>
  );
}
