export const individualStats = [
  {
      "id": 1,
      "name": "Rxfa.RD",
      "rating": 0.98,
      "rounds": 11,
      "kills": 8,
      "deaths": 6,
      "kd_diff": "2",
      "kd_ratio": "133.33%",
      "kpr": "72.73%",
      "headshots": 5,
      "hs_percentage": "45%",
      "entry_kills": 0,
      "entry_deaths": 0,
      "entry_diff": 0,
      "clutches": 1,
      "multikills": 2,
      "plants": 2,
      "disables": 0,
      "kost": 0.73,
      "srv": "45%"
  },
  {
      "id": 2,
      "name": "X.RD",
      "rating": 1.12,
      "rounds": 11,
      "kills": 11,
      "deaths": 5,
      "kd_diff": "6",
      "kd_ratio": "220.00%",
      "kpr": "100.00%",
      "headshots": 4,
      "hs_percentage": "36%",
      "entry_kills": 1,
      "entry_deaths": 0,
      "entry_diff": 1,
      "clutches": 1,
      "multikills": 3,
      "plants": 0,
      "disables": 0,
      "kost": 0.98,
      "srv": "55%"
  },
  {
      "id": 3,
      "name": "SaltyGrain.RD",
      "rating": 0.85,
      "rounds": 11,
      "kills": 10,
      "deaths": 8,
      "kd_diff": "2",
      "kd_ratio": "125.00%",
      "kpr": "90.91%",
      "headshots": 5,
      "hs_percentage": "45%",
      "entry_kills": 3,
      "entry_deaths": 2,
      "entry_diff": 1,
      "clutches": 0,
      "multikills": 4,
      "plants": 0,
      "disables": 0,
      "kost": 0.73,
      "srv": "27%"
  },
  {
      "id": 4,
      "name": "peer.-",
      "rating": 1.33,
      "rounds": 11,
      "kills": 15,
      "deaths": 4,
      "kd_diff": "11",
      "kd_ratio": "375.00%",
      "kpr": "136.36%",
      "headshots": 6,
      "hs_percentage": "55%",
      "entry_kills": 1,
      "entry_deaths": 1,
      "entry_diff": 0,
      "clutches": 1,
      "multikills": 4,
      "plants": 0,
      "disables": 0,
      "kost": 0.88,
      "srv": "64%"
  },
  {
      "id": 5,
      "name": "MLKC.",
      "rating": 1.02,
      "rounds": 11,
      "kills": 10,
      "deaths": 7,
      "kd_diff": "3",
      "kd_ratio": "142.86%",
      "kpr": "90.91%",
      "headshots": 7,
      "hs_percentage": "64%",
      "entry_kills": 3,
      "entry_deaths": 0,
      "entry_diff": 3,
      "clutches": 0,
      "multikills": 2,
      "plants": 0,
      "disables": 0,
      "kost": 0.99,
      "srv": "36%"
  }
]
