# Generated by Django 4.2.5 on 2023-12-15 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoundReplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='replays')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gamereplay')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_own', models.BooleanField()),
                ('score', models.PositiveIntegerField()),
                ('won', models.BooleanField()),
                ('win_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('side', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('replay', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.roundreplay')),
                ('dateTime', models.DateTimeField()),
                ('match_id', models.CharField(max_length=50)),
                ('map', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('own_score', models.PositiveIntegerField()),
                ('opp_score', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(max_length=50)),
                ('own_atk_ban', models.CharField(blank=True, max_length=50, null=True)),
                ('opp_atk_ban', models.CharField(blank=True, max_length=50, null=True)),
                ('own_def_ban', models.CharField(blank=True, max_length=50, null=True)),
                ('opp_def_ban', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('spawn', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=50)),
                ('kills', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('headshots', models.PositiveIntegerField()),
                ('died', models.BooleanField()),
                ('opening_kill', models.BooleanField()),
                ('opening_death', models.BooleanField()),
                ('entry_kill', models.BooleanField()),
                ('entry_death', models.BooleanField()),
                ('refragged', models.BooleanField()),
                ('traded', models.BooleanField()),
                ('planted', models.BooleanField()),
                ('time_of_plant', models.PositiveIntegerField()),
                ('disabled', models.BooleanField()),
                ('time_of_disable', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round'),
        ),
    ]
