# Generated by Django 4.1.1 on 2023-09-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_jsonupload_player_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jsonupload",
            name="uploaded_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
