# Generated by Django 4.2.5 on 2023-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_player_time_of_disable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='spawn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
