# Generated by Django 4.2.5 on 2023-12-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_spawn'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('match_id', 'number'), name='round_id'),
        ),
    ]
