# Generated by Django 4.1.1 on 2023-09-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_uploaded_on_jsonupload_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jsonupload",
            name="file",
            field=models.FileField(upload_to="upload/%Y/%m/%d"),
        ),
    ]
