# Generated by Django 4.1.1 on 2023-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_jsonupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="plants",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="opp_ban",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="game",
            name="own_ban",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="jsonupload",
            name="file",
            field=models.FileField(upload_to="JSON_upload/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="round",
            name="side",
            field=models.CharField(max_length=20),
        ),
    ]
