# Generated by Django 4.2.5 on 2023-12-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_round_round_id_round_unique_round_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundreplay',
            name='game',
        ),
        migrations.AddField(
            model_name='roundreplay',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameReplay',
        ),
    ]
