# Generated by Django 4.1.1 on 2023-09-09 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_game_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="core.game",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Stats",
        ),
    ]
