# Generated by Django 4.1.1 on 2023-09-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_game_date_game_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="opp_ban",
        ),
        migrations.RemoveField(
            model_name="game",
            name="own_ban",
        ),
        migrations.AddField(
            model_name="game",
            name="opp_atk_ban",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="game",
            name="opp_def_ban",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="game",
            name="own_atk_ban",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="game",
            name="own_def_ban",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
